# Generated by Django 4.0.4 on 2022-05-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre libro')),
                ('cantidad', models.CharField(max_length=2, verbose_name='stock libro')),
                ('precio', models.CharField(max_length=10, verbose_name='precio libro')),
                ('comprador', models.CharField(max_length=100, verbose_name='comprador')),
            ],
        ),
    ]
