# Generated by Django 4.0.4 on 2022-05-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='comprador',
        ),
        migrations.AlterField(
            model_name='libro',
            name='cantidad',
            field=models.IntegerField(max_length=2, verbose_name='cantidad libro'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.IntegerField(max_length=10, verbose_name='precio libro'),
        ),
    ]
