# Generated by Django 4.0.4 on 2022-05-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_core', '0003_remove_libro_cantidad_libro_portada_libro_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre libro')),
                ('cantidad', models.IntegerField(max_length=2, null=True, verbose_name='cantidad libro')),
                ('precio', models.CharField(max_length=10, verbose_name='precio libro')),
            ],
        ),
        migrations.AlterField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(max_length=2, null=True, verbose_name='stock libro'),
        ),
    ]
