# Generated by Django 4.0.4 on 2022-05-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_core', '0005_carrito_total_alter_carrito_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.AddField(
            model_name='carrito',
            name='codigoCarrito',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='codigo del carro'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='codigoLibro',
            field=models.CharField(max_length=8, null=True, verbose_name='codigo del libro'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(null=True, verbose_name='cantidad de libros'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='precio',
            field=models.IntegerField(verbose_name='precio unitario'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.IntegerField(verbose_name='precio libro'),
        ),
    ]
