# Generated by Django 4.0.4 on 2022-05-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_core', '0007_alter_carrito_codigocarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='url del libro'),
        ),
    ]
