# Generated by Django 4.0.4 on 2022-05-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_core', '0008_carrito_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='codigoCarrito',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='codigo del carro'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.CharField(max_length=1000000, verbose_name='precio libro'),
        ),
    ]
