# Generated by Django 4.0.4 on 2022-05-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_core', '0009_alter_carrito_codigocarrito_alter_libro_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='url',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='codigoLibro',
        ),
        migrations.AddField(
            model_name='carrito',
            name='codigoLibro',
            field=models.ManyToManyField(to='libreria_core.libro', verbose_name='codigo del libro'),
        ),
    ]
