# Generated by Django 4.0.4 on 2022-06-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_core', '0010_remove_carrito_nombre_remove_carrito_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='codigoLibro',
        ),
    ]
