# Generated by Django 4.0.4 on 2022-06-19 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_core', '0012_remove_carrito_cantidad_carrito_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad del libro')),
                ('codigoCarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria_core.carrito', verbose_name='Codigo del Carro')),
                ('codigoLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria_core.libro', verbose_name='Codigo del Libro')),
            ],
        ),
    ]
