# Generated by Django 4.0.4 on 2022-06-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_core', '0015_alter_libro_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.DateField(null=True, verbose_name='fecha'),
        ),
    ]
